
# Stage 1: Build the application
FROM node:20-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
# Using --legacy-peer-deps for broader compatibility if needed, but try without first.
# If issues arise, consider: RUN npm install --legacy-peer-deps
RUN npm install

# Copy application code (velocity.sqlite is included in this copy)
COPY . .

# Set production environment for build
ENV NODE_ENV production

# Build the Next.js application (this will create the .next/standalone directory)
RUN npm run build

# Stage 2: Create the production image
FROM node:20-alpine AS runner
WORKDIR /app

ENV PORT 3000
ENV NODE_ENV production
ENV ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
ENV MONGODB_URI=${MONGODB_URI}
ENV GEMINI_API_KEY=${GEMINI_API_KEY}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT:-465}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_PASS=${SMTP_PASS}
ENV SENDER_EMAIL=${SENDER_EMAIL}

# Create a non-root user and group for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from the builder stage
# The standalone output copies server.js, .next/static, and public into respective locations.
# Copy the standalone server files
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy public assets
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Set the user to the non-root user
USER nextjs

EXPOSE 3000

# Command to run the Next.js application
# The server.js file is generated by the standalone output and placed in the CWD (/app)
CMD ["node", "server.js"]



